# 2. NumPy 배열
* NumPy에는 **ndarray**라는 데이터 타입의 배열이 사용된다.
* 같은 타입의 데이터만 저장할 수 있다.
* Python list에 비해 계산 속도가 빠르다.


In [1]:
import numpy as np

## 2-1. np.array() 함수로 생성하기

### 1차원 배열 생성하기

In [6]:
# 1차원 배열 생성하기
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [7]:
#type 확인
type(arr)

numpy.ndarray

In [8]:
#array 함수에는 data에 1개만 들어가야 함
#np.array(1, 2, 3, 4)

In [9]:
# 데이터 타입 확인
arr.dtype

dtype('int32')

In [10]:
#overflow 테스트
arr = np.array([2147483647, 2, 3, 4], dtype=np.int32)
arr

array([2147483647,          2,          3,          4])

In [2]:
arr([21474836484, 2, 3, 4], dtype=int32)
arr

NameError: name 'arr' is not defined

In [12]:
arr.dtype
dtype('int64')
arr = np.array([1,2,3,4], dtype=float)
arr

NameError: name 'dtype' is not defined

In [ ]:
##shape : 각 차원의 배열의 size(차원의 모양)
arr.shape

In [ ]:
# size : 배열 전체의 요소의 갯수
arr.size

In [13]:
#ndim : 차원의 수
arr.ndim

1

In [14]:
#ndarray에는 같은 데이터 타입만 들어가야 함
arr = np.array([1,2,33.14])
arr

array([ 1.  ,  2.  , 33.14])

In [15]:
#int, float -> int,
arr = np.array([1,2,3,3.14]), dtype=int
arr

SyntaxError: cannot assign to function call (<ipython-input-15-93638bdfe232>, line 2)

In [ ]:
#int, float, string -> string
# >(big-endian), <(little-endian)
# 32-character string
arr = np.array([1, 3.14, '1234'])
arr = np.array([1, 3.14, '1234567890'])
arr

In [ ]:
# 기존의 배열을 이용하여 타입이 다른 배열을 생성하기
new_arr = arr.astype(float)
new_arr

In [ ]:
arr.dtype, new_arr.dtype

## 2차원 배열 생성하기

In [16]:
arr2 = np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]], dtype=float)
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [17]:
type(arr2)

numpy.ndarray

In [18]:
arr2.dtype, arr2.shape, arr2.size, arr2.ndim

(dtype('float64'), (3, 4), 12, 2)

In [19]:
new_arr2 = arr2.astype(int)
new_arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## 2-2 np.arange() 함수로 생성하기

### 1차원 배열 생성하기

In [20]:
for i in range(1, 11, 2): # 1, 3, 5, 7, 9
    print(i)

1
3
5
7
9


In [21]:
arr = np.arange(1, 11) # 1~10
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr = np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

Parameters
----------
start : number, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : number
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : number, optional
    Spacing between values.  For any output `out`, this is the distance
    between two adjacent values, ``out[i+1]

In [ ]:
arr = np.arange

In [23]:
arr = np.arange

In [24]:
arr = np.arange

In [25]:
arr = np.arange(1, 11, 2)
arr

array([1, 3, 5, 7, 9])

### 2차원 배열 생성하기

In [26]:
arr = np.arange(12) # 0, 11
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
new_arr = arr.reshape((3, 4)) # shape
new_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
# 원본 배열을 변경
arr.shape = (3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 2-3. np.zeros() 함수로 생성

In [29]:
arr=np.zeros(4, dtype=int)
arr

array([0, 0, 0, 0])

In [30]:
arr2=np.zeros?

Docstring:
zeros(shape, dtype=float, order='C')

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Also
--------
zeros_like : Return an array of zeros with shape and type of input.
empty : Return a new uninitialized array.
ones : Return a new array setting values to one.
full : Return a new array of given shape filled with value.

Examples
--------
>>> np.zeros(5)
array([ 0.,  0.,  0.,  0.,  0.])

>>> np.zeros((5,), dtype=int)
array([0, 0, 0, 0, 0])

>>> np.zeros((2, 1))
array([[ 0.],
      

In [ ]:
arr2=np.zeros

In [31]:
arr2=np.zeros

In [32]:
arr2=np.zeros

arr2=np.zeros((3, 4), dtype=int)
arr2

## 2-4. np.ones() 함수로 생성

In [33]:
arr = np.ones(4)
arr

array([1., 1., 1., 1.])

In [34]:
arr2 = np.ones((3, 4), dtype=int)
arr2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

## 2-5. np.linspace() 함수로 생성

In [35]:
arr = np.linspace(0, 10, 5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [36]:
arr = np.linspace(0, 10)
arr

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [37]:
arr.shape

(50,)

In [38]:
# (5,10)인 2차원 배열로 만들기
arr2 = arr.reshape((5. 10))
arr2

SyntaxError: invalid syntax (<ipython-input-38-b1db89eb4a13>, line 2)

## 2-6. np.full() 함수로 생성

In [39]:
arr = np.full ((4, ), 10)
arr

array([10, 10, 10, 10])

In [40]:
arr2 = np.full ((3, 4), 10)
arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

## 2-7. np.eye() 함수로 생성

In [41]:
#단위 행렬, 항등 행렬
arr = np.eye(2)
arr

array([[1., 0.],
       [0., 1.]])

## 2-8. np.random() 으로 생성

In [42]:
arr = np.random.rand(2, 3)
arr

array([[0.00888643, 0.33035258, 0.13455687],
       [0.29621412, 0.43518499, 0.25998699]])

In [43]:
arr = np.random.randint(5, size=10) # 0~4
arr

array([1, 4, 0, 1, 2, 1, 0, 1, 3, 1])

In [44]:
arr = np.random.randint

## 2-9. Numpy 배열 Save & Load

In [45]:
arr = np.arnage(0,5) #0~4
arr

AttributeError: module 'numpy' has no attribute 'arnage'

In [ ]:
np.save('my_arr', arr)

In [46]:
np.save('my_arr')

TypeError: _save_dispatcher() missing 1 required positional argument: 'arr'

In [ ]:
new_arr = np.load('my_arr.npy')
new_arr