# 5. 인덱싱과 슬라이싱

## 5-1. 인덱싱

In [2]:
import numpy as np

In [3]:
arr = np.arange(1, 11) #0~9
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[0], arr[4], arr[-1]

(1, 5, 10)

In [5]:
arr2 = np.arange(1, 13).reshape(3, 4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
arr2[0][1], arr2[1][2], arr2[2][3]

(2, 7, 12)

In [7]:
arr2[0, 1], arr2[1, 2], arr2[2, 3] #numpy에서는 다차원 indexing

(2, 7, 12)

In [8]:
arr2[-1][-2], arr2[-1, -2]

(11, 11)

## 5-2 슬라이싱

### 1차원 배열 

In [9]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
# 3~끝까지 슬라이싱([start;end;step])
arr[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[2:5]

array([3, 4, 5])

In [12]:
#처음~5까지 슬라이싱
arr[:5]

array([1, 2, 3, 4, 5])

In [13]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
# 슬라이싱을 한 후에 값을 변경하면 원본에 영향을 미칠까?
new_arr = arr[:5]
new_arr

array([1, 2, 3, 4, 5])

In [16]:
new_arr[0] = 100
new_arr

array([100,   2,   3,   4,   5])

In [17]:
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [18]:
copy_arr = np.copy(arr)
copy_arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

### 2차원 배열

In [19]:
arr2 = np.arange(1, 13).reshape(3, 4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
# 첫번째 행들 모두 가져오기
arr2[0], arr2[0, :]

(array([1, 2, 3, 4]), array([1, 2, 3, 4]))

In [21]:
#세번째 열을 모두 가져오기
arr2[:, 2]

array([ 3,  7, 11])

In [22]:
# 첫번째, 두번째 행을 모두 가져오기
arr2[ :2 , :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
# 두번째, 세번째 열을 모두 가져오기
arr2[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [25]:
# [[2,3]
  #  [6,7]]
arr2[:2, 1:3]

array([[2, 3],
       [6, 7]])

## 5-3. Fancy 인덱싱

In [26]:
# 1차원 배열
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [27]:
# 1, 3, 5로 된 배열을 만들기
np.array([arr[0], arr[2], arr[4]])

array([100,   3,   5])

In [28]:
#슬라이싱 [start:end:step]
arr[:5:2]

array([100,   3,   5])

In [29]:
# Fancy 인덱싱 (인덱스로 된 배열로 추출)
arr[[0, 2, 4]]

array([100,   3,   5])

In [30]:
# Fancy 인덱싱
arr2[:, [1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [31]:
# 2차원 배열
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
# [[1, 2, 3, 4]
# [9, 10, 11, 12]]
np.array([arr2[0], arr2[2]])

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [33]:
# Fancy 인덱싱
arr2[[0, 2]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [34]:
# 주의
arr2[0, 2] #arr2[0][2]

3

In [35]:
# 슬라이싱
arr2[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [36]:
# Fancy 인덱싱
arr2[: , [1, 2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

## 5-4. Boolean 인덱싱

In [37]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [38]:
#cond = [False, True, False, False, True]
arr[[False, True, False, False, True]]

array([1, 4])

In [39]:
arr > 2

array([False, False, False,  True,  True])

In [40]:
arr[arr > 2]

array([3, 4])

In [41]:
#짝수만 뽑기
arr % 2 == 0

array([ True, False,  True, False,  True])

In [42]:
arr[arr % 2 == 0]

array([0, 2, 4])

In [43]:
#0, 3, 4
arr[(arr < 1) | (arr > 2)]

array([0, 3, 4])

In [44]:
# 2, 3
(arr > 1) & (arr < 4)

array([False, False,  True,  True, False])

In [45]:
arr[(arr > 1) & (arr < 4)]

array([2, 3])