# 6. 실습

In [11]:
# numpy import하기
import numpy as np

## 6-1. NumPy 배열 생성

In [12]:
# np.array()로 1차원 배열 [1, 2, 3, 4, 5] 생성 후 출력하기
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [13]:
# 1차원 배열의 데이터타입, 모양, 배열 전체 element의 수, 차원의 수 출력하기
type(arr) # 데이터타입

numpy.ndarray

In [14]:
arr.shape # 모양

(5,)

In [15]:
arr.size # 배열 전체 element의 수

5

In [16]:
arr.ndim # 차원의 수 출력

1

In [17]:
# np.array()로 아래 2차원 배열 생성 후 출력하기
# [[10, 20, 30, 40],
#  [50, 60, 70, 80]]
arr2 = np.array([[10, 20,30,40],
               [50,60,70,80]], dtype=int)
arr2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [18]:
# np.arange()로 1차원 배열 [1, 2, 3, 4, 5] 생성 후 출력하기
arr = np.arange(1, 6)
arr

array([1, 2, 3, 4, 5])

In [19]:
# np.arange()로 아래 2차원 배열 생성 후 출력하기
# [[10, 20, 30, 40],
#  [50, 60, 70, 80]]
arr = np.arange(10,81,10)
arr

array([10, 20, 30, 40, 50, 60, 70, 80])

In [20]:
# 주사위를 100번 던져서 나오는 숫자 배열 출력하기
np.random.seed(100)
arr = np.random.randint (1, 7, size=100)
arr

array([1, 1, 4, 1, 3, 5, 3, 6, 3, 3, 3, 2, 1, 1, 5, 4, 5, 3, 1, 4, 2, 6,
       3, 4, 5, 5, 2, 6, 6, 4, 5, 5, 4, 4, 4, 2, 2, 6, 4, 1, 3, 2, 2, 4,
       3, 6, 4, 1, 2, 1, 6, 5, 3, 1, 1, 3, 6, 3, 2, 1, 6, 3, 2, 6, 5, 3,
       1, 4, 4, 4, 6, 1, 6, 2, 5, 3, 4, 4, 5, 3, 5, 4, 2, 1, 5, 4, 5, 6,
       3, 3, 5, 3, 6, 5, 2, 3, 3, 1, 3, 3])

In [21]:
# np.random을 사용하여 랜덤 실수값으로 이루어진 (3, 4) 2차원 배열 생성
arr = np.random.rand(3, 4)
arr

array([[0.363188  , 0.20434528, 0.27676506, 0.24653588],
       [0.173608  , 0.96660969, 0.9570126 , 0.59797368],
       [0.73130075, 0.34038522, 0.0920556 , 0.46349802]])

## 6-2. 산술연산

In [22]:
# [1, 2, 3, 4, 5], [6, 7, 8, 9, 10] 1차원 배열 2개를 생성하고 출력하기
a = np.arange(1, 6)
b = np.arange(6, 11)
a,b

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [23]:
# 1차원 배열간 산술연산(덧셈, 뺄셈, 곱셈, 나눗셈) 하기
a + b # 덧셈

array([ 7,  9, 11, 13, 15])

In [24]:
a - b # 뺄셈

array([-5, -5, -5, -5, -5])

In [25]:
a * b # 곱셈

array([ 6, 14, 24, 36, 50])

In [26]:
a / b # 나눗셈

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [69]:
# [[1, 2, 3, 4, 5]   [[11, 12, 13, 14, 15]
#  [6, 7, 8, 9, 10]], [16, 17, 18, 19, 20]] 2차원 배열 2개를 생성하고 출력하기
a = np.arange(1,11).reshape(2,5)
b = np.arange(11,21).reshape(2,5)
a, b

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]))

In [70]:
# 2차원 배열간 산술연산(덧셈, 뺄셈, 나눗셈) 하기
a+b, a-b, a/b, a*b

(array([[12, 14, 16, 18, 20],
        [22, 24, 26, 28, 30]]),
 array([[-10, -10, -10, -10, -10],
        [-10, -10, -10, -10, -10]]),
 array([[0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333],
        [0.375     , 0.41176471, 0.44444444, 0.47368421, 0.5       ]]),
 array([[ 11,  24,  39,  56,  75],
        [ 96, 119, 144, 171, 200]]))

In [71]:
# 두번째 배열의 shape을 (5, 2)로 만들고 출력하기
new_arr = b.reshape(5,2)
new_arr

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [73]:
# 행렬곱셈(dot product) 연산하기
np.dot(a, new_arr)

array([[245, 260],
       [620, 660]])

## 6-3. Aggregation 함수

In [31]:
# 1~10까지 이루어진 1차원 배열 생성하기
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
# 최대값, 최소값 출력하기
a.max(), a.min()

(10, 1)

In [33]:
# 배열요소의 합, 평균값 출력하기
 # 배열요소의 합

In [34]:
np.mean(a) # 평균값

5.5

In [35]:
# 중앙값(중위값), 표준편차 출력하기
np.median(a) # 중앙값(중위값)

5.5

In [36]:
np.std(a) # 표준편차

2.8722813232690143

In [48]:
# 1~20까지 이루어진 2차원 배열 (4, 5) 생성하기
a = np.arange(1, 21).reshape(4, 5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [55]:
# 각 행의 max값, min값 출력하기
np.max(a, axis=0), np.min(a, axis=1) #행(row)

(array([16, 17, 18, 19, 20]), array([ 1,  6, 11, 16]))

In [56]:
# 각 열의 max값, min값 출력하기
np.max(a, axis=1), np.min(a, axis=1)#열(column)


(array([ 5, 10, 15, 20]), array([ 1,  6, 11, 16]))

In [53]:
# 각 행의 sum값 출력하기
np.sum(a, axis=1)

array([15, 40, 65, 90])

In [54]:
# 각 열의 sum값 출력하기
np.sum(a, axis = 0)

array([34, 38, 42, 46, 50])

## 6-4. 정렬

In [42]:
# 1~100까지 랜덤 정수값을 갖는 1차원 배열 (10, ) 생성하기
# seed값 100부여하기
np.random.seed(100)
arr = np.random.randint (1, 100, size=(10, )) #1~9, 10개
arr

array([ 9, 25, 68, 88, 80, 49, 11, 95, 53, 99])

In [43]:
# 위 1차원 배열을 오름차순 정렬하기
np.sort(arr)

array([ 9, 11, 25, 49, 53, 68, 80, 88, 95, 99])

In [44]:
# 위 1차원 배열을 내림차순 정렬하기
np.sort(arr)[::-1]

array([99, 95, 88, 80, 68, 53, 49, 25, 11,  9])

In [45]:
# 랜덤 seed값 100부여하기
# 1~100까지 랜덤 정수값을 갖는 2차원 배열 (5, 10) 생성하기
np.random.seed(100)
arr2 = np.random.randint(1, 100, size=(5, 10))
arr2

array([[ 9, 25, 68, 88, 80, 49, 11, 95, 53, 99],
       [54, 67, 99, 15, 35, 25, 16, 61, 59, 17],
       [10, 94, 87,  3, 28,  5, 32,  2, 14, 84],
       [ 5, 92, 60, 68,  8, 50, 48, 66, 62, 15],
       [56, 72, 81,  3, 95, 20, 99, 64, 54, 28]])

In [46]:
# 열 기준 정렬하기
np.sort(arr2)

array([[ 9, 11, 25, 49, 53, 68, 80, 88, 95, 99],
       [15, 16, 17, 25, 35, 54, 59, 61, 67, 99],
       [ 2,  3,  5, 10, 14, 28, 32, 84, 87, 94],
       [ 5,  8, 15, 48, 50, 60, 62, 66, 68, 92],
       [ 3, 20, 28, 54, 56, 64, 72, 81, 95, 99]])

In [47]:
# 행 기준 정렬하기
np.sort(arr2, axis=0)

array([[ 5, 25, 60,  3,  8,  5, 11,  2, 14, 15],
       [ 9, 67, 68,  3, 28, 20, 16, 61, 53, 17],
       [10, 72, 81, 15, 35, 25, 32, 64, 54, 28],
       [54, 92, 87, 68, 80, 49, 48, 66, 59, 84],
       [56, 94, 99, 88, 95, 50, 99, 95, 62, 99]])

## 6-5. 인덱싱과 슬라이싱

In [182]:
# 0~14로 이루어진 2차원 배열 (3, 5) 생성하기
arr = np.arange(1, 15) #0~9
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [183]:
# 위 배열에서 7을 인덱싱하기
arr[7]

8

In [184]:
# 위 배열에서 14를 인덱싱하기 (음수 인덱스 사용)
arr[-14]

1

In [169]:
# 위 배열에서 배열 [6, 7]을 슬라이싱하기
arr[6:7]

array([], shape=(0, 5), dtype=int32)

In [177]:
# 위 배열에서 배열 [7, 12]을 슬라이싱하기
new_arr = arr[7:12]
new_arr

array([], shape=(0, 5), dtype=int32)

In [89]:
# 위 배열에서 [[3, 4], [8, 9]]을 슬라이싱하기
new_arr[3:4], new_arr[8:9]
new_arr

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [83]:
# 위 배열에서 3의 배수 찾기
new_arr % 3 == 0

array([[False,  True],
       [False, False],
       [ True, False],
       [False,  True],
       [False, False]])

In [86]:
# 위 배열에서 4로 나누면 1이 남는 수 찾기
new_arr % 4 == 1

array([[False, False],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False]])

In [85]:
# 위 배열에서 3의 배수이면서 4로 나누면 1이 남는 수 찾기
new_arr % 3 == 0, new_arr % 4 == 1

(array([[False,  True],
        [False, False],
        [ True, False],
        [False,  True],
        [False, False]]),
 array([[False, False],
        [ True, False],
        [False, False],
        [ True, False],
        [False, False]]))